package addonpacks.BionicleQuestForNuicraftPalladium.addon.bionicleqfn_palladium.init;

public class BionicleQFNPalladiumBlocks {
    public static final DeferredRegister<Block> REGISTRY;
    public static final RegistryObject<Block> MASK_FORGE;
    public static final RegistryObject<Block> ONU_WAHI_STONE_ORE;
    public static final RegistryObject<Block> LIGHTSTONES_ORE   
    public static final RegistryObject<Block> LIGHTSTONES_BLOCK;
    public static final RegistryObject<Block> MATA_NUI_STONE;
    public static final RegistryObject<Block> MAKUTA_STONE;
    public static final RegistryObject<Block> PROTODERMIS;
    public static final RegistryObject<Block> LIGHT_GRAY_STONE;
    public static final RegistryObject<Block> BLACK_STONE;
    public static final RegistryObject<Block> GA_KORO_STONE;
    public static final RegistryObject<Block> SEAWEED_BLOCK;
    public static final RegistryObject<Block> SEAWEED_FLOWER_BLOCK;
    public static final RegistryObject<Block> SEAWEED_PLANKS;
    public static final RegistryObject<Block> SEAWEED_WOOD_WOOD;
    public static final RegistryObject<Block> SEAWEED_WOOD_LOG;
    public static final RegistryObject<Block> SEAWEED_WOOD_PLANKS;
    public static final RegistryObject<Block> SEAWEED_WOOD_LEAVES;
    public static final RegistryObject<Block> SEAWEED_WOOD_STAIRS;
    public static final RegistryObject<Block> SEAWEED_WOOD_SLAB;
    public static final RegistryObject<Block> SEAWEED_WOOD_FENCE;
    public static final RegistryObject<Block> SEAWEED_WOOD_FENCE_GATE;
    public static final RegistryObject<Block> SEAWEED_WOOD_PRESSURE_PLATE;
    public static final RegistryObject<Block> SEAWEED_WOOD_BUTTON;
    public static final RegistryObject<Block> PROTODERMIS_ORE;
    public static final RegistryObject<Block> ONU_KORO_STONE;
    public static final RegistryObject<Block> TA_KORO_STONE;
    public static final RegistryObject<Block> PROTODERMIS_BLOCK;
    public static final RegistryObject<Block> BLACK_STONE_BLOCK;
    public static final RegistryObject<Block> ICE_WOOD;
    public static final RegistryObject<Block> ICE_PLANKS;
    public static final RegistryObject<Block> ICE_STAIRS;
    public static final RegistryObject<Block> ICE_SLAB;
    public static final RegistryObject<Block> ICE_FENCE;
    public static final RegistryObject<Block> ICE_FENCE_GATE;
    public static final RegistryObject<Block> ICE_PRESSURE_PLATE;
    public static final RegistryObject<Block> ICE_BUTTON;
    public static final RegistryObject<Block> BLACK_STONE_STAIRS;
    public static final RegistryObject<Block> BLACK_STONE_SLAB;
    public static final RegistryObject<Block> BLACK_STONE_FENCE;
    public static final RegistryObject<Block> BLACK_STONE_FENCE_GATE;
    public static final RegistryObject<Block> BLACK_STONE_PRESSURE_PLATE;
    public static final RegistryObject<Block> BLACK_STONE_BUTTON;
    public static final RegistryObject<Block> BLACK_STONE_BRICK;
    public static final RegistryObject<Block> BLACK_STONE_LAMP;
    public static final RegistryObject<Block> KO_KORO_STONE;
    public static final RegistryObject<Block> PROTOSTEEL_BLOCK;
    public static final RegistryObject<Block> LIGHT_GRAY_STONE_BRICK;
    public static final RegistryObject<Block> LIGHT_GRAY_STONE_STAIRS;
    public static final RegistryObject<Block> LIGHT_GRAY_STONE_SLAB;
    public static final RegistryObject<Block> PO_KORO_STONE;
    public static final RegistryObject<Block> LE_KORO_STONE;
    public static final RegistryObject<Block> LIGHTGRAYSTONE_PLANKS;
    public static final RegistryObject<Block> LIGHTGRAYSTONE_FENCE;
    public static final RegistryObject<Block> LIGHTGRAYSTONE_FENCE_GATE;
    public static final RegistryObject<Block> LIGHTGRAYSTONE_PRESSURE_PLATE;
    public static final RegistryObject<Block> LIGHTGRAYSTONE_BUTTON;
    public static final RegistryObject<Block> LIGHT_GRAY_TOA_STONE_STAIRS;
    public static final RegistryObject<Block> LIGHT_GRAY_TOA_STONE_SLAB;
    public static final RegistryObject<Block> CURED_WOOD_WOOD;
    public static final RegistryObject<Block> CURED_WOOD_LOG;
    public static final RegistryObject<Block> CURED_WOOD_PLANKS;
    public static final RegistryObject<Block> CURED_WOOD_LEAVES;
    public static final RegistryObject<Block> CURED_WOOD_STAIRS;
    public static final RegistryObject<Block> CURED_WOOD_SLAB;
    public static final RegistryObject<Block> CURED_WOOD_FENCE;
    public static final RegistryObject<Block> CURED_WOOD_FENCE_GATE;
    public static final RegistryObject<Block> CURED_WOOD_PRESSURE_PLATE;
    public static final RegistryObject<Block> CURED_WOOD_BUTTON;
    public static final RegistryObject<Block> LE_KORO_LADDER;
    public static final RegistryObject<Block> SNOW_WALL_TEXT_BLOCK;
    public static final RegistryObject<Block> SNOW_WALL_TEXT_BLOCK_2;

    static {
        REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, "bionicleqfn_palladium");
        MASK_FORGE = REGISTRY.register("mask_forge", () -> new MaskForgeBlock());
        ONU_WAHI_STONE_ORE = REGISTRY.register("onu_wahi_stone_ore", () -> new OnuWahiStoneOreBlock());
        LIGHTSTONES_ORE = REGISTRY.register("lightstones_ore", () -> new LightstonesOreBlock());
        LIGHTSTONES_BLOCK = REGISTRY.register("lightstones_block", () -> new LightstonesBlockBlock());
        MATA_NUI_STONE = REGISTRY.register("mata_nui_stone", () -> new MataNuiStoneBlock());
        MAKUTA_STONE = REGISTRY.register("makuta_stone", () -> new MakutaStoneBlock());
        PROTODERMIS = REGISTRY.register("protodermis", () -> new ProtodermisBlock());
        LIGHT_GRAY_STONE = REGISTRY.register("light_gray_stone", () -> new LightGrayStoneBlock());
        BLACK_STONE = REGISTRY.register("black_stone", () -> new BlackStoneBlock());
        GA_KORO_STONE = REGISTRY.register("ga_koro_stone", () -> new GaKoroStoneBlock());
        SEAWEED_BLOCK = REGISTRY.register("seaweed_block", () -> new SeaweedBlockBlock());
        SEAWEED_FLOWER_BLOCK = REGISTRY.register("seaweed_flower_block", () -> new SeaweedFlowerBlockBlock());
        SEAWEED_PLANKS = REGISTRY.register("seaweed_planks", () -> new SeaweedPlanksBlock());
        SEAWEED_WOOD_WOOD = REGISTRY.register("seaweed_wood_wood", () -> new SeaweedWoodWoodBlock());
        SEAWEED_WOOD_LOG = REGISTRY.register("seaweed_wood_log", () -> new SeaweedWoodLogBlock());
        SEAWEED_WOOD_PLANKS = REGISTRY.register("seaweed_wood_planks", () -> new SeaweedWoodPlanksBlock());
        SEAWEED_WOOD_LEAVES = REGISTRY.register("seaweed_wood_leaves", () -> new SeaweedWoodLeavesBlock());
        SEAWEED_WOOD_STAIRS = REGISTRY.register("seaweed_wood_stairs", () -> new SeaweedWoodStairsBlock());
        SEAWEED_WOOD_SLAB = REGISTRY.register("seaweed_wood_slab", () -> new SeaweedWoodSlabBlock());
        SEAWEED_WOOD_FENCE = REGISTRY.register("seaweed_wood_fence", () -> new SeaweedWoodFenceBlock());
        SEAWEED_WOOD_FENCE_GATE = REGISTRY.register("seaweed_wood_fence_gate", () -> new SeaweedWoodFenceGateBlock());
        SEAWEED_WOOD_PRESSURE_PLATE = REGISTRY.register("seaweed_wood_pressure_plate", () -> new SeaweedWoodPressurePlateBlock());
        SEAWEED_WOOD_BUTTON = REGISTRY.register("seaweed_wood_button", () -> new SeaweedWoodButtonBlock());
        PROTODERMIS_ORE = REGISTRY.register("protodermis_ore", () -> new ProtodermisOreBlock());
        ONU_KORO_STONE = REGISTRY.register("onu_koro_stone", () -> new OnuKoroStoneBlock());
        TA_KORO_STONE = REGISTRY.register("ta_koro_stone", () -> new TaKoroStoneBlock());
        PROTODERMIS_BLOCK = REGISTRY.register("protodermis_block", () -> new ProtodermisBlockBlock());
        BLACK_STONE_BLOCK = REGISTRY.register("black_stone_block", () -> new BlackStoneBlockBlock());
        ICE_WOOD = REGISTRY.register("ice_wood", () -> new IceWoodBlock());
        ICE_PLANKS = REGISTRY.register("ice_planks", () -> new IcePlanksBlock());
        ICE_STAIRS = REGISTRY.register("ice_stairs", () -> new IceStairsBlock());
        ICE_SLAB = REGISTRY.register("ice_slab", () -> new IceSlabBlock());
        ICE_FENCE = REGISTRY.register("ice_fence", () -> new IceFenceBlock());
        ICE_FENCE_GATE = REGISTRY.register("ice_fence_gate", () -> new IceFenceGateBlock());
        ICE_PRESSURE_PLATE = REGISTRY.register("ice_pressure_plate", () -> new IcePressurePlateBlock());
        ICE_BUTTON = REGISTRY.register("ice_button", () -> new IceButtonBlock());
        BLACK_STONE_STAIRS = REGISTRY.register("black_stone_stairs", () -> new BlackStoneStairsBlock());
        BLACK_STONE_SLAB = REGISTRY.register("black_stone_slab", () -> new BlackStoneSlabBlock());
        BLACK_STONE_FENCE = REGISTRY.register("black_stone_fence", () -> new BlackStoneFenceBlock());
        BLACK_STONE_FENCE_GATE = REGISTRY.register("black_stone_fence_gate", () -> new BlackStoneFenceGateBlock());
        BLACK_STONE_PRESSURE_PLATE = REGISTRY.register("black_stone_pressure_plate", () -> new BlackStonePressurePlateBlock());
        BLACK_STONE_BUTTON = REGISTRY.register("black_stone_button", () -> new BlackStoneButtonBlock());
        BLACK_STONE_BRICK = REGISTRY.register("black_stone_brick", () -> new BlackStoneBrickBlock());
        BLACK_STONE_LAMP = REGISTRY.register("black_stone_lamp", () -> new BlackStoneLampBlock());
        KO_KORO_STONE = REGISTRY.register("ko_koro_stone", () -> new KoKoroStoneBlock());
        PROTOSTEEL_BLOCK = REGISTRY.register("protosteel_block", () -> new ProtosteelBlockBlock());
        LIGHT_GRAY_STONE_BRICK = REGISTRY.register("light_gray_stone_brick", () -> new LightGrayStoneBrickBlock());
        LIGHT_GRAY_STONE_STAIRS = REGISTRY.register("light_gray_stone_stairs", () -> new LightGrayStoneStairsBlock());
        LIGHT_GRAY_STONE_SLAB = REGISTRY.register("light_gray_stone_slab", () -> new LightGrayStoneSlabBlock());
        PO_KORO_STONE = REGISTRY.register("po_koro_stone", () -> new PoKoroStoneBlock());
        LE_KORO_STONE = REGISTRY.register("le_koro_stone", () -> new LeKoroStoneBlock());
        LIGHTGRAYSTONE_PLANKS = REGISTRY.register("lightgraystone_planks", () -> new LightgraystonePlanksBlock());
        LIGHTGRAYSTONE_FENCE = REGISTRY.register("lightgraystone_fence", () -> new LightgraystoneFenceBlock());
        LIGHTGRAYSTONE_FENCE_GATE = REGISTRY.register("lightgraystone_fence_gate", () -> new LightgraystoneFenceGateBlock());
        LIGHTGRAYSTONE_PRESSURE_PLATE = REGISTRY.register("lightgraystone_pressure_plate", () -> new LightgraystonePressurePlateBlock());
        LIGHTGRAYSTONE_BUTTON = REGISTRY.register("lightgraystone_button", () -> new LightgraystoneButtonBlock());
        LIGHT_GRAY_TOA_STONE_STAIRS = REGISTRY.register("light_gray_toa_stairs", () -> new LightGrayToaStoneStairsBlock());
        LIGHT_GRAY_TOA_STONE_SLAB = REGISTRY.register("light_gray_toa_slab", () -> new LightGrayToaStoneSlabBlock());
        CURED_WOOD_WOOD = REGISTRY.register("cured_wood_wood", () -> new CuredWoodWoodBlock());
        CURED_WOOD_LOG = REGISTRY.register("cured_wood_log", () -> new CuredWoodLogBlock());
        CURED_WOOD_PLANKS = REGISTRY.register("cured_wood_planks", () -> new CuredWoodPlanksBlock());
        CURED_WOOD_LEAVES = REGISTRY.register("cured_wood_leaves", () -> new CuredWoodLeavesBlock());
        CURED_WOOD_STAIRS = REGISTRY.register("cured_wood_stairs", () -> new CuredWoodStairsBlock());
        CURED_WOOD_SLAB = REGISTRY.register("cured_wood_slab", () -> new CuredWoodSlabBlock());
        CURED_WOOD_FENCE = REGISTRY.register("cured_wood_fence", () -> new CuredWoodFenceBlock());
        CURED_WOOD_FENCE_GATE = REGISTRY.register("cured_wood_fence_gate", () -> new CuredWoodFenceGateBlock());
        CURED_WOOD_PRESSURE_PLATE = REGISTRY.register("cured_wood_pressure_plate", () -> new CuredWoodPressurePlateBlock());
        CURED_WOOD_BUTTON = REGISTRY.register("cured_wood_button", () -> new CuredWoodButtonBlock());
        LE_KORO_LADDER = REGISTRY.register("le_koro_ladder", () -> new LeKoroLadderBlock());
        SNOW_WALL_TEXT_BLOCK = REGISTRY.register("snow_wall_text_block", () -> new SnowWallTextBlockBlock());
        SNOW_WALL_TEXT_BLOCK_2 = REGISTRY.register("snow_wall_text_block_2", () -> new SnowWallTextBlock2Block());
    }
}
